version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  app_back:
    build: ./back
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports: 
      - 3000:3000

  app_front:
    build: ./front
    depends_on:
      - mysqldb
      - app_back
    links:
      - mysqldb
      - app_back
    ports: 
      - 8080:8080
